### ISSUE TITLE
Dummy issue: For testing the closing of issues from PR.

### ISSUE THREAD

**Issue by MithunKinarullathil** [MOV-AI/movai-flow#144]
- Dummy issue.

**Comment by AlexFernandes-MOVAI** [comment]
come on, so many issues you could have spotted instead of a dummy one ;)

**Comment by MithunKinarullathil** [comment]
Haha, I wish I could solve the other ones :laughing:

**Comment by MithunKinarullathil** [comment]
The issue is only closed if a merge to the default branch is mentioned using the keywords. Since the default branch is main, this does not work with the current settings. @AlexFernandes-MOVAI Possible to change the default branch to dev? In other repos we use we have this and do not break the pipelines etc.
